# Generated by Django 5.1.6 on 2025-02-07 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enable', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('method', models.CharField(default='chacha20-ietf-poly1305', max_length=50)),
                ('sub_id', models.CharField(max_length=255, unique=True)),
                ('tg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_gb', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sniffing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('dest_override', models.JSONField(default=list)),
                ('metadata_only', models.BooleanField(default=False)),
                ('route_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StreamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(default='none', max_length=50)),
                ('network', models.CharField(default='tcp', max_length=50)),
                ('tcp_settings', models.JSONField(default=dict)),
                ('kcp_settings', models.JSONField(blank=True, default=dict, null=True)),
                ('external_proxy', models.JSONField(blank=True, default=list, null=True)),
                ('reality_settings', models.JSONField(blank=True, default=dict, null=True)),
                ('xtls_settings', models.JSONField(blank=True, default=dict, null=True)),
                ('tls_settings', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decryption', models.CharField(blank=True, max_length=255, null=True)),
                ('fallbacks', models.JSONField(blank=True, default=list, null=True)),
                ('clients', models.ManyToManyField(to='vpn.client')),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('up', models.BigIntegerField(default=0)),
                ('down', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('expiry_time', models.BigIntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.settings')),
                ('sniffing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.sniffing')),
                ('stream_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.streamsettings')),
            ],
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'user')},
            },
        ),
    ]
