# Generated by Django 5.1.6 on 2025-02-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='down',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='expiry_time',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='protocol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='remark',
            field=models.CharField(default='SS', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inbound',
            name='total',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='up',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
